name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install terser for minification
        run: npm install --save-dev terser

      - name: Build
        run: npm run build

      - name: Create required files
        run: |
          # Create .nojekyll file
          touch dist/.nojekyll
          
          # Create 404.html from index.html
          cp dist/index.html dist/404.html
          
          # Create a root index.html redirect
          echo '<!DOCTYPE html><html><head><meta charset="utf-8"><title>Redirecting to Lennert Bikes</title><script>window.location.href = "/lennert-bikes/";</script><meta http-equiv="refresh" content="0; url=/lennert-bikes/"></meta></head><body>If you are not redirected automatically, <a href="/lennert-bikes/">click here</a>.</body></html>' > dist/index.html
          
          # Copy 404.html from public if it exists
          if [ -f "public/404.html" ]; then
            cp public/404.html dist/404.html
          fi

      - name: Debug - List files
        run: |
          ls -la dist/
          echo "Deployment files ready"

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          clean: true
          clean-exclude: |
            .nojekyll 